/// Liste exacte des 109 genres proposés par le filtre `genre[]` de /catalogue
/// (extraite du formulaire du site le 02/09/2026).
const List<String> kGenres = [
  'Action',
  'Adolescence',
  'Aliens / Extra-terrestres',
  'Amitié',
  'Amour',
  'Apocalypse',
  'Art',
  'Arts martiaux',
  'Assassinat',
  'Autre monde',
  'Aventure',
  'Combats',
  'Comédie',
  'Crime',
  'Cyberpunk',
  'Danse',
  'Démons',
  'Détective',
  'Donghua',
  'Dragon',
  'Drame',
  'Ecchi',
  'Ecole',
  'Elfe',
  'Enquête',
  'Famille',
  'Fantastique',
  'Fantasy',
  'Fantômes',
  'Futur',
  'Gastronomie',
  'Ghibli',
  'Guerre',
  'Harcèlement',
  'Harem',
  'Harem inversé',
  'Histoire',
  'Historique',
  'Homosexualité',
  'Horreur',
  'Isekai',
  'Jeunesse',
  'Jeux',
  'Jeux vidéo',
  'Josei',
  'Journalisme',
  'Kaï',
  'LGBT+',
  'Mafia',
  'Magical girl',
  'Magie',
  'Maladie',
  'Mariage',
  'Mature',
  'Mechas',
  'Médiéval',
  'Militaire',
  'Monde virtuel',
  'Monstres',
  'Musique',
  'Mystère',
  'Nekketsu',
  'Ninjas',
  'Nostalgie',
  'Paranormal',
  'Philosophie',
  'Pirates',
  'Police',
  'Politique',
  'Post-apocalyptique',
  'Pouvoirs psychiques',
  'Préhistoire',
  'Prison',
  'Psychologique',
  'Quotidien',
  'Religion',
  'Réincarnation / Transmigration',
  'Romance',
  'Samouraïs',
  'School Life',
  'Science-Fantasy',
  'Science-fiction',
  'Scientifique',
  'Seinen',
  'Shôjo',
  'Shôjo-Ai',
  'Shônen',
  'Shônen-Ai',
  'Slice of Life',
  'Société',
  'Sport',
  'Super pouvoirs',
  'Super-héros',
  'Surnaturel',
  'Survie',
  'Survival game',
  'Technologies',
  'Thriller',
  'Tournois',
  'Travail',
  'Vampires',
  'Vengeance',
  'Voyage',
  'Voyage temporel',
  'Webcomic',
  'Yakuza',
  'Yaoi',
  'Yokai',
  'Yuri',
];

/// Valeurs acceptées par `type[]`.
const List<String> kCatalogueTypes = ['Anime', 'Scans', 'Film', 'Autres'];

/// Valeurs acceptées par `langue[]`.
const List<String> kCatalogueLangs = ['VOSTFR', 'VF', 'VASTFR'];

/// Valeurs acceptées par `current[]`.
const List<String> kCatalogueStatus = ['En cours', 'Terminé'];
